ikigailabs/ikigai-superset

- superset-frontend/src/dashboard/stylesheets/dashboard.less
- superset/db_engine_specs/base.py
Accidentally forked our already forked repo and started working on that, after this I will delete my fork and work only on this one :)
Main Commits:
1> Setup raw error message capturing and set potential code as comments
2> Added custom dashboard.less and ikigai.png files to superset
> Cloning my fork to company fork

- superset-frontend/src/dashboard/components/gridComponents/IkiProcessBuilder.jsx
- superset-frontend/src/dashboard/components/gridComponents/IkiRunPipeline.jsx
- superset-frontend/src/dashboard/components/gridComponents/IkiTable.jsx
Update iframe url if cluster_id exists in top window.
Custom components should adopt if cluster_id is available
> [UIUX-610] cluster_id for custom components

- superset-frontend/src/dashboard/components/Header/HeaderActionsDropdown/HeaderActionsDropdown.test.tsx
- superset-frontend/src/dashboard/components/Header/HeaderActionsDropdown/index.jsx
- superset-frontend/src/dashboard/components/SliceHeaderControls/SliceHeaderControls.test.tsx
- superset-frontend/src/dashboard/components/SliceHeaderControls/index.tsx
- superset-frontend/src/dashboard/components/gridComponents/IkiProcessBuilder.jsx
- superset-frontend/src/dashboard/components/gridComponents/IkiRunPipeline.jsx
- superset-frontend/src/dashboard/components/gridComponents/IkiTable.jsx
- superset-frontend/src/explore/components/ExploreAdditionalActionsMenu/ExploreAdditionalActionsMenu.test.tsx
- superset-frontend/src/explore/components/ExploreAdditionalActionsMenu/index.jsx
- superset-frontend/src/explore/components/controls/DatasourceControl/index.jsx
- superset/config.py
> Ikigailabs dev

- superset-frontend/src/dashboard/components/Header/HeaderActionsDropdown/HeaderActionsDropdown.test.tsx
- superset-frontend/src/dashboard/components/Header/HeaderActionsDropdown/index.jsx
- superset-frontend/src/dashboard/components/SliceHeaderControls/SliceHeaderControls.test.tsx
- superset-frontend/src/dashboard/components/SliceHeaderControls/index.tsx
- superset-frontend/src/explore/components/ExploreAdditionalActionsMenu/ExploreAdditionalActionsMenu.test.tsx
- superset-frontend/src/explore/components/ExploreAdditionalActionsMenu/index.jsx
> Un-hiding 'Export CSV' and 'Download as Image' options

- superset-frontend/src/dashboard/components/gridComponents/IkiProcessBuilder.jsx
- superset-frontend/src/dashboard/components/gridComponents/IkiTable.jsx
> [UIUX-651] - added redirect for process diagram + editable table custom components

- superset-frontend/src/dashboard/components/gridComponents/IkiProcessBuilder.jsx
- superset-frontend/src/dashboard/components/gridComponents/IkiRunPipeline.jsx
- superset-frontend/src/dashboard/components/gridComponents/IkiTable.jsx
> [UIUX-651] - reverting iframe src urls back to url w/o redirect

- superset-frontend/src/dashboard/components/gridComponents/IkiProcessBuilder.jsx
- superset-frontend/src/dashboard/components/gridComponents/IkiRunPipeline.jsx
- superset-frontend/src/dashboard/components/gridComponents/IkiTable.jsx
> [UIUX-651] - iframe src url fix

- superset-frontend/src/dashboard/components/gridComponents/IkiProcessBuilder.jsx
- superset-frontend/src/dashboard/components/gridComponents/IkiRunPipeline.jsx
- superset-frontend/src/dashboard/components/gridComponents/IkiTable.jsx
> [UIUX-651] - revert iframe src url back to /redirect?

- superset-frontend/src/components/PageHeaderWithActions/index.tsx
- superset-frontend/src/dashboard/stylesheets/dashboard.less
> dev to prod

- superset-frontend/src/dashboard/components/gridComponents/IkiRunPipeline.jsx
Remove old name parameters and make url always same format
> [UIUX-751] run flow btn cleanup

- superset-frontend/src/components/PageHeaderWithActions/index.tsx
- superset-frontend/src/dashboard/stylesheets/dashboard.less
Run flow btn cleanup
Keep run flow btn url format always the same
Versioning info
Remove old url parameters like pipeline_name and project_name
> Run flow btn cleanup

- superset-frontend/src/dashboard/components/gridComponents/IkiProcessBuilder.jsx
- superset-frontend/src/dashboard/components/gridComponents/IkiRunPipeline.jsx
- superset-frontend/src/dashboard/components/gridComponents/IkiTable.jsx
cluster id catching from superset iframe url
> cluster id catching from superset iframe url

- superset-frontend/src/components/PageHeaderWithActions/index.tsx
> Fix edit-dashboard flex layout

- superset-frontend/src/components/Modal/Modal.tsx
- superset-frontend/src/components/PageHeaderWithActions/index.tsx
- superset-frontend/src/dashboard/components/DashboardGrid.jsx
- superset-frontend/src/dashboard/components/gridComponents/IkiProcessBuilder.jsx
> prod to dev

- superset-frontend/packages/superset-ui-core/src/style/index.tsx
- superset-frontend/src/dashboard/components/Header/HeaderActionsDropdown/index.jsx
- superset-frontend/src/dashboard/components/Header/index.jsx
- superset-frontend/src/dashboard/stylesheets/dashboard.less
> Enable top-right More menu

- superset-frontend/packages/superset-ui-chart-controls/src/shared-controls/index.tsx
- superset-frontend/src/explore/controls.jsx
> [UIUX-861][feature][1] Hiding time grain

- superset-frontend/src/dashboard/components/Header/HeaderActionsDropdown/index.jsx
This reverts commit 9e0395e093c8f1b58b8af3d3ec9d6d39e723f7ea.
> Revert "[UIUX-825] css customization"

- superset-frontend/src/views/components/Menu.test.tsx
- superset-frontend/src/views/components/Menu.tsx
> merging dev to prod 

- superset-frontend/src/dashboard/components/DashboardBuilder/DashboardBuilder.tsx
- superset-frontend/src/dashboard/components/nativeFilters/FilterBar/FilterControls/FilterControls.tsx
- superset-frontend/src/dashboard/components/nativeFilters/FilterBar/Header/index.tsx
- superset-frontend/src/dashboard/components/nativeFilters/FilterBar/index.tsx
- superset-frontend/src/dashboard/constants.ts
- superset-frontend/src/dashboard/stylesheets/dashboard.less
Added filter bar to right sidepanel
> [IPLT-3287] - Added filter bar to right sidepanel + tweaked css

- superset-frontend/src/components/PageHeaderWithActions/index.tsx
- superset-frontend/src/dashboard/components/DashboardBuilder/DashboardBuilder.tsx
- superset-frontend/src/dashboard/components/DashboardBuilder/state.ts
- superset-frontend/src/dashboard/constants.ts
> [IPLT-3287] - dashboard filter bar UI tweaks

- superset-frontend/src/dashboard/components/DashboardBuilder/DashboardBuilder.tsx
> [IPLT-3367] - merge dashboard ui/ux improvements without filter bar

- superset-frontend/src/dashboard/components/gridComponents/IkiRunPipeline.jsx
> charts encoding hotfix

- superset-frontend/src/dashboard/components/BuilderComponentPane/index.tsx
- superset-frontend/src/dashboard/components/gridComponents/new/DraggableNewComponent.jsx
- superset-frontend/src/dashboard/components/gridComponents/new/NewColumn.jsx
- superset-frontend/src/dashboard/components/gridComponents/new/NewDeepCast.jsx
- superset-frontend/src/dashboard/components/gridComponents/new/NewDivider.jsx
- superset-frontend/src/dashboard/components/gridComponents/new/NewHeader.jsx
- superset-frontend/src/dashboard/components/gridComponents/new/NewIkiEitlColumn.jsx
- superset-frontend/src/dashboard/components/gridComponents/new/NewIkiEitlRow.jsx
- superset-frontend/src/dashboard/components/gridComponents/new/NewIkiProcessBuilder.jsx
- superset-frontend/src/dashboard/components/gridComponents/new/NewIkiRunPipeline.jsx
- superset-frontend/src/dashboard/components/gridComponents/new/NewIkiTable.jsx
- superset-frontend/src/dashboard/components/gridComponents/new/NewMarkdown.jsx
- superset-frontend/src/dashboard/components/gridComponents/new/NewRow.jsx
- superset-frontend/src/dashboard/components/gridComponents/new/NewTabs.jsx
- superset-frontend/src/dashboard/stylesheets/components/new-component.less
- superset-frontend/src/dashboard/stylesheets/dashboard.less
> [IPLT-4477] - Restructure Superset component sidebar
